name: Failure to Issue
on:
  workflow_run:
    workflows: ["CI","E2E","Lighthouse","Deploy to Azure SWA"]
    types: [completed]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  file-issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Open failure issue
        id: open_issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          title: "Build failure: ${{ github.event.workflow_run.name }} (#${{ github.event.workflow_run.run_number }})"
          body:  "Run: ${{ github.event.workflow_run.html_url }}\nBranch: ${{ github.event.workflow_run.head_branch }}\n\nPlease investigate."
          labels: "broken,windsorfollowup"
      - name: Append task to AGENT_TASKS.md
        run: |
          f=AGENT_TASKS.md
          [ ! -f "$f" ] && echo -e "# Agent Tasks (source of truth)\n\n## Queue\n\n## Done" > "$f"
          ins="- [ ] Investigate CI failure: ${{ github.event.workflow_run.name }} — ${{ github.event.workflow_run.html_url }}"
          awk -v ins="$ins" 'BEGIN{p=0} /^## Queue/ && !p {print; print ins; p=1; next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
      - name: Open PR for queue update
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: AGENT_TASKS.md
          branch: ws-ci-fail/${{ github.run_id }}
          commit-message: "chore(queue): CI failure follow-up"
          title: "chore(queue): CI failure follow-up"
          body: "Auto-generated from failing run: ${{ github.event.workflow_run.html_url }}"
          labels: automerge
